# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
construct_sigma1 <- function(sig_all, rho) {
    .Call('_lvmcorr_construct_sigma1', PACKAGE = 'lvmcorr', sig_all, rho)
}

#' @export
fisher_z_trans <- function(z) {
    .Call('_lvmcorr_fisher_z_trans', PACKAGE = 'lvmcorr', z)
}

#' @export 
mean_diff_nonzero <- function(x, j) {
    .Call('_lvmcorr_mean_diff_nonzero', PACKAGE = 'lvmcorr', x, j)
}

sample_g_b <- function(g, g_free_ind, xi, x_covariates, ytp, yfp, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, e_tp, e_fp, e12, sig2_tp, sig2_fp, rho) {
    invisible(.Call('_lvmcorr_sample_g_b', PACKAGE = 'lvmcorr', g, g_free_ind, xi, x_covariates, ytp, yfp, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, e_tp, e_fp, e12, sig2_tp, sig2_fp, rho))
}

#' @export
lvmcorr_cpp <- function(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e_tp, e_fp, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose = FALSE) {
    .Call('_lvmcorr_lvmcorr_cpp', PACKAGE = 'lvmcorr', ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e_tp, e_fp, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose)
}

lvmcorr_multi_chains <- function(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, chains = 1L) {
    .Call('_lvmcorr_lvmcorr_multi_chains', PACKAGE = 'lvmcorr', ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, chains)
}

#' @export
lvmcorr_seperate_fin_cpp <- function(ytp_all, yfp_all, x_covariates, b_tp, b_fp, g, g_free_ind, e1234, xi, beta_tp_all, alpha_tp_all, beta_fp_all, alpha_fp_all, u_tp, u_fp, mcmc_len, verbose = FALSE) {
    .Call('_lvmcorr_lvmcorr_seperate_fin_cpp', PACKAGE = 'lvmcorr', ytp_all, yfp_all, x_covariates, b_tp, b_fp, g, g_free_ind, e1234, xi, beta_tp_all, alpha_tp_all, beta_fp_all, alpha_fp_all, u_tp, u_fp, mcmc_len, verbose)
}

#' @export
lvmcorr_seperate_fin_cpp1 <- function(ytp_all, yfp_all, x_covariates, b_tp, b_fp, g, g_free_ind, e1234, xi, beta_tp_all, alpha_tp_all, beta_fp_all, alpha_fp_all, u_tp, u_fp, mcmc_len, verbose = FALSE) {
    .Call('_lvmcorr_lvmcorr_seperate_fin_cpp1', PACKAGE = 'lvmcorr', ytp_all, yfp_all, x_covariates, b_tp, b_fp, g, g_free_ind, e1234, xi, beta_tp_all, alpha_tp_all, beta_fp_all, alpha_fp_all, u_tp, u_fp, mcmc_len, verbose)
}

#' @export
lvmcorr_seperate_fin_general <- function(ytp_all, yfp_all, x_covariates, rho_covs, b_tp, b_fp, g, g_free_ind, e1234, sig_init, beta_rho_init, xi, beta_tp_all, alpha_tp_all, beta_fp_all, alpha_fp_all, u_tp, u_fp, rho_stepsize, mcmc_len, verbose = FALSE) {
    .Call('_lvmcorr_lvmcorr_seperate_fin_general', PACKAGE = 'lvmcorr', ytp_all, yfp_all, x_covariates, rho_covs, b_tp, b_fp, g, g_free_ind, e1234, sig_init, beta_rho_init, xi, beta_tp_all, alpha_tp_all, beta_fp_all, alpha_fp_all, u_tp, u_fp, rho_stepsize, mcmc_len, verbose)
}

#' @export 
getlvmcorr_threads <- function() {
    .Call('_lvmcorr_getlvmcorr_threads', PACKAGE = 'lvmcorr')
}

#' @export 
setlvmcorr_threads <- function(threads) {
    .Call('_lvmcorr_setlvmcorr_threads', PACKAGE = 'lvmcorr', threads)
}

#' @export
sample_alpha_beta <- function(alpha_tpfp, beta_tpfp, ytpfp, eta_tpfp) {
    invisible(.Call('_lvmcorr_sample_alpha_beta', PACKAGE = 'lvmcorr', alpha_tpfp, beta_tpfp, ytpfp, eta_tpfp))
}

#' @export
sample_eta <- function(eta_tpfp, ytpfp, beta_tpfp, alpha_tpfp) {
    invisible(.Call('_lvmcorr_sample_eta', PACKAGE = 'lvmcorr', eta_tpfp, ytpfp, beta_tpfp, alpha_tpfp))
}

sample_b_tp_c <- function(b_tp, ytp, xi, x_covariates, beta_tp, alpha_tp, e_tp, e1) {
    .Call('_lvmcorr_sample_b_tp_c', PACKAGE = 'lvmcorr', b_tp, ytp, xi, x_covariates, beta_tp, alpha_tp, e_tp, e1)
}

sample_b_fp_c <- function(b_fp, yfp, xi, x_covariates, beta_fp, alpha_fp, e_fp, e2) {
    .Call('_lvmcorr_sample_b_fp_c', PACKAGE = 'lvmcorr', b_fp, yfp, xi, x_covariates, beta_fp, alpha_fp, e_fp, e2)
}

sample_b_linear_reg <- function(e_tp1, e_tp2, e_fp2, x_covariates1, x_covariates2, b_tp, b_fp, sig2_tp, sig2_fp, rho) {
    .Call('_lvmcorr_sample_b_linear_reg', PACKAGE = 'lvmcorr', e_tp1, e_tp2, e_fp2, x_covariates1, x_covariates2, b_tp, b_fp, sig2_tp, sig2_fp, rho)
}

sample_b_tp_new <- function(Sigma, e1234, x_covariates, b_tp) {
    .Call('_lvmcorr_sample_b_tp_new', PACKAGE = 'lvmcorr', Sigma, e1234, x_covariates, b_tp)
}

sample_b_fp_new <- function(Sigma, e1234, x_covariates, b_fp) {
    .Call('_lvmcorr_sample_b_fp_new', PACKAGE = 'lvmcorr', Sigma, e1234, x_covariates, b_fp)
}

sample_e_tp_c <- function(e_tp, ytp, xi, b_tp, sig2_tp, beta_tp, alpha_tp, x_covariates) {
    .Call('_lvmcorr_sample_e_tp_c', PACKAGE = 'lvmcorr', e_tp, ytp, xi, b_tp, sig2_tp, beta_tp, alpha_tp, x_covariates)
}

sample_e_fp_c <- function(e_fp, yfp, xi, b_fp, sig2_fp, beta_fp, alpha_fp, x_covariates) {
    .Call('_lvmcorr_sample_e_fp_c', PACKAGE = 'lvmcorr', e_fp, yfp, xi, b_fp, sig2_fp, beta_fp, alpha_fp, x_covariates)
}

sample_e12_c <- function(e12, ytp, yfp, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, sig2_tp, sig2_fp, rho, b_tp, b_fp, x_covariates) {
    .Call('_lvmcorr_sample_e12_c', PACKAGE = 'lvmcorr', e12, ytp, yfp, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, sig2_tp, sig2_fp, rho, b_tp, b_fp, x_covariates)
}

#' @export 
test1 <- function(tmp, y_i) {
    .Call('_lvmcorr_test1', PACKAGE = 'lvmcorr', tmp, y_i)
}

#' @export 
test2 <- function(tmp, y_i) {
    .Call('_lvmcorr_test2', PACKAGE = 'lvmcorr', tmp, y_i)
}

#' @export 
test13 <- function(tmp, tail) {
    .Call('_lvmcorr_test13', PACKAGE = 'lvmcorr', tmp, tail)
}

sample_g_c <- function(g, g_free_ind, xi, x_covariates) {
    .Call('_lvmcorr_sample_g_c', PACKAGE = 'lvmcorr', g, g_free_ind, xi, x_covariates)
}

sample_sig2_tp_c <- function(sig2_tp, sig2_fp, rho, e_tp, e12, xi) {
    .Call('_lvmcorr_sample_sig2_tp_c', PACKAGE = 'lvmcorr', sig2_tp, sig2_fp, rho, e_tp, e12, xi)
}

sample_sig2_fp_c <- function(sig2_tp, sig2_fp, rho, e_fp, e12, xi) {
    .Call('_lvmcorr_sample_sig2_fp_c', PACKAGE = 'lvmcorr', sig2_tp, sig2_fp, rho, e_fp, e12, xi)
}

sample_rho_c <- function(rho, xi, sig2_tp, sig2_fp, e12) {
    .Call('_lvmcorr_sample_rho_c', PACKAGE = 'lvmcorr', rho, xi, sig2_tp, sig2_fp, e12)
}

#' @export
log_rho_export <- function(x, rho_loc, e1234, sig2_tp, sig2_fp, rho) {
    .Call('_lvmcorr_log_rho_export', PACKAGE = 'lvmcorr', x, rho_loc, e1234, sig2_tp, sig2_fp, rho)
}

sample_Sigma_new1 <- function(e1234) {
    .Call('_lvmcorr_sample_Sigma_new1', PACKAGE = 'lvmcorr', e1234)
}

#' @export
sample_rho <- function(e1234, sig_all, rho, step_rho) {
    invisible(.Call('_lvmcorr_sample_rho', PACKAGE = 'lvmcorr', e1234, sig_all, rho, step_rho))
}

#' @export
sample_sig2 <- function(e1234, sig_all, rho, step_sigma) {
    invisible(.Call('_lvmcorr_sample_sig2', PACKAGE = 'lvmcorr', e1234, sig_all, rho, step_sigma))
}

#' @export
sample_sig2_sep <- function(e1234_1, e1234_2, sig_all, rho1, rho2, step_sigma) {
    invisible(.Call('_lvmcorr_sample_sig2_sep', PACKAGE = 'lvmcorr', e1234_1, e1234_2, sig_all, rho1, rho2, step_sigma))
}

#' @export
sample_u_c <- function(ytp_fin, x_covariates, u_tp, sig2_u_tp) {
    .Call('_lvmcorr_sample_u_c', PACKAGE = 'lvmcorr', ytp_fin, x_covariates, u_tp, sig2_u_tp)
}

#' @export
sample_sig2_u <- function(u_tp) {
    .Call('_lvmcorr_sample_sig2_u', PACKAGE = 'lvmcorr', u_tp)
}

#' @export
test_inv_gamma <- function(alpha, beta, nn) {
    .Call('_lvmcorr_test_inv_gamma', PACKAGE = 'lvmcorr', alpha, beta, nn)
}

#' @export
my_trunc_norm <- function(mu, direction) {
    .Call('_lvmcorr_my_trunc_norm', PACKAGE = 'lvmcorr', mu, direction)
}

sample_u_tp_new <- function(Sigma, e1234, u_tp, x_covariates) {
    .Call('_lvmcorr_sample_u_tp_new', PACKAGE = 'lvmcorr', Sigma, e1234, u_tp, x_covariates)
}

sample_u_fp_new <- function(Sigma, e1234, u_fp, x_covariates) {
    .Call('_lvmcorr_sample_u_fp_new', PACKAGE = 'lvmcorr', Sigma, e1234, u_fp, x_covariates)
}

#' @export 
test3 <- function(mu, sig2, cut_point, direct, n) {
    .Call('_lvmcorr_test3', PACKAGE = 'lvmcorr', mu, sig2, cut_point, direct, n)
}

#' @export
sample_e1234 <- function(e1234, ytp, yfp, ytp_fin, yfp_fin, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, u_tp, u_fp, x_covariates, Sigma) {
    invisible(.Call('_lvmcorr_sample_e1234', PACKAGE = 'lvmcorr', e1234, ytp, yfp, ytp_fin, yfp_fin, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, u_tp, u_fp, x_covariates, Sigma))
}

sample_e1234_general <- function(e1234, ytp, yfp, ytp_fin, yfp_fin, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, u_tp, u_fp, x_covariates, sig_all, rho_mat) {
    invisible(.Call('_lvmcorr_sample_e1234_general', PACKAGE = 'lvmcorr', e1234, ytp, yfp, ytp_fin, yfp_fin, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, u_tp, u_fp, x_covariates, sig_all, rho_mat))
}

sample_xi <- function(x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, e_tp, yfp, b_fp, e_fp, e12) {
    .Call('_lvmcorr_sample_xi', PACKAGE = 'lvmcorr', x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, e_tp, yfp, b_fp, e_fp, e12)
}

#' @export
print_prob_m1 <- function(x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, yfp, b_fp, ytp_fin, u_tp, yfp_fin, u_fp, e1234) {
    .Call('_lvmcorr_print_prob_m1', PACKAGE = 'lvmcorr', x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, yfp, b_fp, ytp_fin, u_tp, yfp_fin, u_fp, e1234)
}

#' @export
print_prob_m <- function(x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, yfp, b_fp, ytp_fin, u_tp, yfp_fin, u_fp, e1234) {
    .Call('_lvmcorr_print_prob_m', PACKAGE = 'lvmcorr', x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, yfp, b_fp, ytp_fin, u_tp, yfp_fin, u_fp, e1234)
}

